NODE_TYPE_ID=r4.2xlarge
NODE_TYPE_ID_APP_LAUNCH_FEATURE_ENGINEERING_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_APP_LAUNCH_FEATURE_ENGINEERING_CLUSTER=r4.2xlarge
NODE_TYPE_ID_AGG_ML_EMAIL_METRICS_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_AGG_ML_EMAIL_METRICS_CLUSTER=r4.2xlarge
NODE_TYPE_ID_APP_LAUNCH_MONETA_VALIDATION_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_APP_LAUNCH_MONETA_VALIDATION_CLUSTER=r4.2xlarge
NODE_TYPE_ID_APP_LAUNCH_DLQ_VALIDATION_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_APP_LAUNCH_DLQ_VALIDATION_CLUSTER=r4.2xlarge
NODE_TYPE_ID_APP_LAUNCH_PREDICTION_PIPELINE_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_APP_LAUNCH_PREDICTION_PIPELINE_CLUSTER=r4.2xlarge
