NODE_TYPE_ID=m4.large
DRIVER_NODE_TYPE_ID_APP_LAUNCH_FEATURE_ENGINEERING_CLUSTER=r4.2xlarge
DRIVER_NODE_TYPE_ID_AGG_ML_EMAIL_METRICS_CLUSTER=r4.2xlarge
min_workers=5
max_workers=6
S3_PATH=s3://prod-bucket/data
DB_URL=jdbc:mysql://prod-db-host:3306/db
OPERATION_MODE=prod
DB_SECRETS_SCOPE=aws ssm getparameter prod xd
S3_READ_PREFIX=reads3 prod
S3_WRITE_PREFIX=writes3 prod

